title: Harsiddh Tamboli # your name (or website title) here
logo: "/images/my_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With 1+ years of experience as an Associate Data Analyst, I can 
  bring my expertise and analytical approach to take data-driven 
  solution using Python, SQL and google spreadsheet.
  <br><br>
  Still on a run to learn.
  <br><br>
  <a href = "https://www.linkedin.com/in/harsiddh-tamboli-602073183/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-H72PKTEP4H # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
